#:schema node_modules/wrangler/config-schema.json
name = "amway-image-generator"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[ai]
binding = "AI"

[[r2_buckets]]
bucket_name = "ai-img-playground"
binding = "BUCKET"

# Campaign storage bucket for ZIP files
[[r2_buckets]]
bucket_name = "amway-campaigns"
binding = "CAMPAIGN_STORAGE"

# D1 database for product data and campaigns
[[d1_databases]]
binding = "DB"
database_name = "amway-image-gen"
database_id = "a045519c-a814-4160-8bbe-5b3a4df6c55b"

[vars]
CLOUDFLARE_ACCOUNT_ID = "dc56444c4c955a1653106ccf997c1067"
CAMPAIGN_EXPIRY_HOURS = "24"
MAX_IMAGES_PER_CAMPAIGN = "15"
