#:schema node_modules/wrangler/config-schema.json
name = "amway-imagen"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

# Explicitly configure as Workers (not Pages)
[build]
command = "npm run build:worker"

[ai]
binding = "AI"

[[r2_buckets]]
bucket_name = "ai-img-playground"
binding = "BUCKET"

# Campaign storage bucket for ZIP files
[[r2_buckets]]
bucket_name = "amway-campaigns"
binding = "CAMPAIGN_STORAGE"

# D1 database for product data and campaigns
[[d1_databases]]
binding = "DB"
database_name = "amway-image-gen"
database_id = "a045519c-a814-4160-8bbe-5b3a4df6c55b"

# Analytics and observability
[observability]
enabled = true

# Logpush for structured logging (optional - requires additional setup)
# [logpush]
# enabled = true

[vars]
CLOUDFLARE_ACCOUNT_ID = "dc56444c4c955a1653106ccf997c1067"
CAMPAIGN_EXPIRY_HOURS = "24"
MAX_IMAGES_PER_CAMPAIGN = "15"
# Scraping configuration
SCRAPING_CACHE_HOURS = "24"
SCRAPING_RATE_LIMIT = "10"
# Environment for logging
NODE_ENV = "production"

# Secrets (set with: wrangler secret put CLAUDE_API_KEY)
# CLAUDE_API_KEY = "sk-ant-..."  # Set via wrangler secret put
